### ISSUE TITLE
Remove ID's from dashboard

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#10]
remove Patient ID from dashboard ob visits 
![capture](https://cloud.githubusercontent.com/assets/19813369/25864960/f8b760fa-34f9-11e7-9d8e-2ee81d4abc7b.jpg)

**Comment by Magik3a** [comment]
![image](https://cloud.githubusercontent.com/assets/10474555/26031604/ef0dd7f0-3882-11e7-9148-e90658554f23.png)
