### ISSUE TITLE
Add Import Export for .ics files

### ISSUE THREAD

**Issue by Magik3a** [Magik3a/PatientManagement_Admin#134]
The export functionality is working and is tested with Outllook and Google Calendar, It needs to be extanded!

Admin button: 
![image](https://user-images.githubusercontent.com/10474555/30955302-d59c0b28-a43b-11e7-9afc-f2fea15e169f.png)

Result Outlook
![image](https://user-images.githubusercontent.com/10474555/30955322-e58882b4-a43b-11e7-9eeb-0926bd257ace.png)

Result Google 
![image](https://user-images.githubusercontent.com/10474555/30955343-f380d114-a43b-11e7-95d3-57255dc0324f.png)

**Comment by Magik3a** [comment]
Now the system support creating links for external sites and exports the calendars in ICS and Json
![image](https://user-images.githubusercontent.com/10474555/31183372-0cb6f940-a92f-11e7-83f7-6b0b83eb49ed.png)

**Comment by Magik3a** [comment]
Are we need to import events from google calendar and others? @ipbg 
If no, we can close this issue becouse the export functions are working correct

**Comment by ipbg** [comment]
Not for now. I think if there is a client which depends on that, may be than we can do it!
