### ISSUE TITLE
Create "Terms Of Use" For Admin Site

### ISSUE THREAD

**Issue by Magik3a** [Magik3a/PatientManagement_Admin#137]

**Comment by Magik3a** [comment]
![image](https://user-images.githubusercontent.com/10474555/31182884-b93d8140-a92d-11e7-80e4-76656b4336b8.png)

**Comment by ipbg** [comment]
Conversation with a lawyer who will write terms and conditions.

**Comment by ipbg** [comment]
[ОБЩИ УСЛОВИЯ CLARIO Finale.pdf](https://github.com/Magik3a/PatientManagement_Admin/files/1446668/CLARIO.Finale.pdf)
