### ISSUE TITLE
Create Invoice for payments 

### ISSUE THREAD

**Issue by Magik3a** [Magik3a/PatientManagement_Admin#142]
This is the generated report now 
![image](https://user-images.githubusercontent.com/10474555/31316765-d1c88b58-ac3c-11e7-9141-58f9956c2236.png)

**Comment by Magik3a** [comment]
You close the issue? Can you send me the invoice to template to add it in admin? I will reopen this for now

**Comment by ipbg** [comment]
![platekno](https://user-images.githubusercontent.com/30435456/31510062-431d1c2c-af8c-11e7-8f46-064abbd7d88c.png)

**Comment by ipbg** [comment]
It will be better if sender name and IBAN automatically appear.

**Comment by ipbg** [comment]
admin must upload invoice after payment

**Comment by Magik3a** [comment]
Implemented dialog for new payment 
![image](https://user-images.githubusercontent.com/10474555/31587113-66fe7640-b1e4-11e7-9ff5-b66efc297212.png)

Implemented coupons for discount on payment in %
![image](https://user-images.githubusercontent.com/10474555/31587158-26953da4-b1e5-11e7-9eac-f7fb9eac0651.png)

**Comment by Magik3a** [comment]
Added payment blank
![image](https://user-images.githubusercontent.com/10474555/31588327-dd70d566-b1f8-11e7-98a4-b5e185f3f914.png)

**Comment by Magik3a** [comment]
Implemented
