### ISSUE TITLE
Company party

### ISSUE THREAD

**Issue by ipbg** [Magik3a/PatientManagement_Admin#155]
Tomorrow 20.00 https://www.google.bg/maps/place/%D0%91%D0%B8%D1%80%D0%B0%D1%80%D0%B8%D1%8F+J%C3%A4gerhof/@42.1416648,24.7895725,15z/data=!4m5!3m4!1s0x0:0x5f80c4aecb13b476!8m2!3d42.1416648!4d24.7895725
Celebrating prise of Bitcoin. 
You are more than welcome.

**Comment by Magik3a** [comment]
It sounds really cool, and the prize now i think hits around 10k lv :D

**Comment by ipbg** [comment]
Yea but for the only one piece of it. :)
Are you coming?
