### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by ipbg** [Magik3a/PatientManagement_Admin#163]
When the subscription is expired client could not do a new subscription or a new payment.

![image](https://user-images.githubusercontent.com/30435456/31664043-994d8ec4-b34c-11e7-8aa5-d80634ddb388.png)

**Comment by Magik3a** [comment]
caused by permissions. When the user subscription is expired, the users is autmaticly in expired role 
fixed
![image](https://user-images.githubusercontent.com/10474555/31665033-3f043c8e-b350-11e7-8445-65ce7da34846.png)
