### ISSUE TITLE
user mail issue

### ISSUE THREAD

**Issue by VaskoIP** [Magik3a/PatientManagement_Admin#164]
New visit error, only in case when patient have an email

[04.pdf](https://github.com/Magik3a/PatientManagement_Admin/files/1391067/04.pdf)

**Comment by Magik3a** [comment]
Implemented. Added validation rule on save or update.
![image](https://user-images.githubusercontent.com/10474555/31678838-07d19f4a-b378-11e7-9d3d-726b160292c7.png)

**Comment by ipbg** [comment]
I think it is still a problem or may ne a I have a problem with cache
