### ISSUE TITLE
Add doctor dropdown in visit dialog 

### ISSUE THREAD

**Issue by tedynceto** [Magik3a/PatientManagement_Admin#177]
когато се добавя нова визита освен посочването на кабинет, ще е добре да се добави и поле в което може да се посочи при кой доктор конкретно иска да се запази час.

**Comment by Magik3a** [comment]
За момента към кабинет мисля че е достатъчно , ако се добави пациент към доктор, ще трябва да решим какво да е поведението на календара и в страницата визити (показваме ли всички или само тези които са на логнатия доктор)

**Comment by Magik3a** [comment]
Implemented  in #188
![image](https://user-images.githubusercontent.com/10474555/35486203-3e62a706-0473-11e8-9fc8-561e986ddf6e.png)
![image](https://user-images.githubusercontent.com/10474555/35486208-4c156b54-0473-11e8-80b8-24bd9c9c71ac.png)
