### ISSUE TITLE
Logo for CLARIO

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#28]
we need some really astonish and eye catching logo in here

**Comment by PetyaWebDesign** [comment]
![clario-logo-large](https://cloud.githubusercontent.com/assets/19813369/26491636/19c83040-4219-11e7-8462-383c9e681dcd.png)
![clario-logo-medium](https://cloud.githubusercontent.com/assets/19813369/26491634/19c53318-4219-11e7-8d42-b483b3dbdec6.png)
![clario-logo-small](https://cloud.githubusercontent.com/assets/19813369/26491635/19c6babc-4219-11e7-80d1-94fc316bbc84.png)

**Comment by Magik3a** [comment]
The new logo and icons are the best!
