### ISSUE TITLE
Add "new visit"button on patient profile

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#34]
on patient profile we need button to add new visit

![image](https://cloud.githubusercontent.com/assets/19813369/26506271/99593986-4254-11e7-9893-12b597dfe342.png)

**Comment by Magik3a** [comment]
the patient already have this button 
![image](https://user-images.githubusercontent.com/10474555/26864195-787811ec-4b5f-11e7-9aa6-93b2f75ddc7a.png)
