### ISSUE TITLE
Idea for user menu organization

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#38]
Perhaps we can create the design as it follow. 
On the left side of the screen. On the top - name of the doctor and image. 
Bellow how many visits he/she have.

![image](https://cloud.githubusercontent.com/assets/19813369/26522478/92cf96b2-430a-11e7-8608-ca788fb989f4.png)

**Comment by Magik3a** [comment]
Implemented 
![image](https://user-images.githubusercontent.com/10474555/33529575-60ea3812-d87b-11e7-9683-25efa684d1fc.png)
![image](https://user-images.githubusercontent.com/10474555/33529578-661bc1de-d87b-11e7-8239-b4af2a0bdf42.png)
