### ISSUE TITLE
Add new menu item in left menu for reports

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#44]
Option for user to open new page with all saved reports (how many patients they have, saved visits, demographic info and other metricks...)

**Comment by PetyaWebDesign** [comment]
![image](https://cloud.githubusercontent.com/assets/19813369/26665184/71d3b67a-46a0-11e7-9e3d-b51950eba62d.png)

**Comment by Magik3a** [comment]
this is currently possible after version 1.2.600. 
Price per visit type is added and patient location is integrated with google 
for diagrams will be used 
https://ecomfe.github.io/echarts-examples/public/index.html

**Comment by Magik3a** [comment]
Implemented 
![chartsclario](https://user-images.githubusercontent.com/10474555/36942693-fda244ae-1f81-11e8-90f2-8bcb654c7031.png)

**Comment by Magik3a** [comment]
implemented new top menu with permissions and color from the choosed theme 
![image](https://user-images.githubusercontent.com/10474555/36995863-f4d5ce3a-20bd-11e8-8dd0-5891f1783a8f.png)

**Comment by Magik3a** [comment]
![image](https://user-images.githubusercontent.com/10474555/36996290-13cc49d0-20bf-11e8-945f-5e6a0f0d3f59.png)
