### ISSUE TITLE
Clean PatientsRepository

### ISSUE THREAD

**Issue by Magik3a** [Magik3a/PatientManagement_Admin#48]
Empty entities should not be created when patient is inserted. Clean next code in PatientsRepository and fix typescript loading on entity dialog!

![image](https://cloud.githubusercontent.com/assets/10474555/26736864/79588b2e-47d0-11e7-8b9b-1cb00540953a.png)

**Comment by Magik3a** [comment]
Please test this in the tab in patients dialog @ipbg 

![image](https://user-images.githubusercontent.com/10474555/31704820-a5e499a8-b3eb-11e7-9ee8-bc53f11c6a55.png)

**Comment by ipbg** [comment]
I create new anamneza and edit old one everything looks ok.

**Comment by Magik3a** [comment]
Ok, i will implement it for other 2 tabs: Activty and Life style
right?

**Comment by ipbg** [comment]
Test it again. It is ok

**Comment by Magik3a** [comment]
When there is a changes in the issue i will add coment

**Comment by Magik3a** [comment]
implemented 
![patient](https://user-images.githubusercontent.com/10474555/31783187-0f468936-b506-11e7-853e-93a0146870b2.gif)
