### ISSUE TITLE
Add option for more than one doctor in one account

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#58]
Add a function which will allow use of the system for more than one doctor.
Each patient and visit can be assigned to different predefined doctors.
For that purpose create new tab in the main menu called "Doctors" (or any related) and new page on which we can see each one of the doctors for a single clinic.

When someone add new patient/visit they can choose from drop down menu for which doctor should be assigned.

**Comment by Magik3a** [comment]
Best decision that i can think is to create something like Cabinets, user can be assignet to cabinet and visit will be assignet to cabinet. That way i can try to filter the dashboard with Dynamic menu from the left....
