### ISSUE TITLE
Combine two fields in one

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#6]
Combine field "Movements" and field "Trainings" to one field (движения и тренировки)

**Comment by Magik3a** [comment]
Combined and moved to another table (Activity)
![image](https://cloud.githubusercontent.com/assets/10474555/26031626/74c832dc-3883-11e7-862c-c8f80851be02.png)

Still the data from LifeStyle needs to be copied, after that i will create a migration for removing fields(Movement (Lifestyle tbl), Training (Lifestyle tbl) and DailyMealfs (PatientHealth tbl))
