### ISSUE TITLE
Add User (doctor) profile

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#64]
Add new tab in the left menu called "my profile".
Option to upload new image, edit name, telephone etc.

**Comment by Magik3a** [comment]
Current status 
![image](https://user-images.githubusercontent.com/10474555/30148130-b7f10b74-93aa-11e7-8948-6ca78509ee40.png)

**Comment by Magik3a** [comment]
fix and add functionalities for editing tenant (with permissions) and user profile. The second form for tenant is example of that with service request (now its really easy for that after update 3.0.4)

**Comment by Magik3a** [comment]
Add dropdowns for work hours, the calendar majorly depends on this one
