### ISSUE TITLE
Add Subscriptions to Tenants 

### ISSUE THREAD

**Issue by Magik3a** [Magik3a/PatientManagement_Admin#74]
This will be major change. 
1.  Define clean approach and add specifications @PetyaWebDesign

**Comment by PetyaWebDesign** [comment]
Create invoicing / payment template as follows:
- Beneficiary name;
- Bank name;
- IBAN of Beneficient;
- reason of payment оr Details of Payment (here we'll include tenant ID number and he/she will gave it as a reason of payment);
- Ordering customer (the one who send us money);
-
