### ISSUE TITLE
Order tabs

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#9]
Tabs on patient folder to be:
Patient -> Patient Health (Анамнеза) -> Lifestyle -> Activities (нов таб, има го в отделно issue) - >Notes - > Visits - >Documents

**Comment by Magik3a** [comment]
![image](https://cloud.githubusercontent.com/assets/10474555/26031581/c024763e-3881-11e7-940f-98a6ff0c665a.png)
